create fallback env variables, convert jsons to lowercase
lesterfernandez/roommate-finder pull request #32
Opened 2023-10-11 20:04 UTC by JrodanDiaz

## Summary

- Created a func that returns a default env variable, if the env variable isn't found
- Converted the json's in queries.go to lowercase for the front-end

2023-10-11 20:59 UTC, lesterfernandez requested changes

2023-10-11 20:59 UTC, lesterfernandez commented on server/data/db.go
> +func getEnv(key string, fallback interface{}) interface{} {
I love that you made a helper function for this. The only issue would be the return type.

According to the [docs](https://pkg.go.dev/os#Getenv), `os.Getenv` only returns a `string` and never an `int`.
So maybe using `interface{}` is no needed? After all, using `interface{}` makes you lose all type information (think pure JavaScript lol).

2023-10-12 18:48 UTC, JrodanDiaz commented
- Changed the type of `fallback` and return type of `getEnv()` to string

2023-10-16 00:36 UTC, lesterfernandez approved these changes

2023-10-16 00:36 UTC, merged